---
name: silver-landing-page-dev
services:
  app:
    container_name: silver-landing-page-dev-c
    image: silver-landing-page-dev-i
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - "3042:3000"
