---
name: silver-landing-page-prod
services:
  app:
    container_name: silver-landing-page-prod-c
    image: silver-landing-page-prod-i:3.7
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
        - "8069:80"
    volumes:
      - ./data:/usr/share/nginx/html/data

# docker image tag silver-landing-page-prod-i:3.7 silveira42/landing-page:3.7
# docker image tag silver-landing-page-prod-i:3.7 silveira42/landing-page:latest
# docker push silveira42/landing-page:3.7
# docker push silveira42/landing-page:latest
